import type {
  Customer,
  DashboardSnapshot,
  EmailUpdate,
  Insight,
  InventoryItem,
  MenuItem,
  Order,
  OrderStatusEvent,
} from "@/types/domain";

const now = "2026-03-17T21:00:00.000Z";

const orders: Order[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    orderNumber: "MG-1051",
    customerId: "cust-201",
    customerName: "Ayesha Khan",
    customerEmail: "ayesha@example.com",
    customerZone: "Herndon",
    status: "Ready",
    serviceDate: "2026-03-17",
    legacyDropDay: "Wednesday",
    fulfillmentMethod: "pickup",
    serviceWindow: "Pickup details confirmed after checkout",
    totalCents: 5512,
    customRequest: "No utensils please. Call on arrival.",
    paymentProvider: "Stripe",
    paymentStatus: "paid",
    createdAt: now,
    updatedAt: now,
    items: [
      {
        id: "oi-1",
        orderId: "11111111-1111-1111-1111-111111111111",
        menuItemId: "nihari-tacos",
        name: "Nihari Tacos",
        quantity: 2,
        notes: "Extra green chutney",
        unitPriceCents: 1800,
      },
      {
        id: "oi-2",
        orderId: "11111111-1111-1111-1111-111111111111",
        menuItemId: "bowl-lamb",
        name: "Lamb Bowl",
        quantity: 1,
        notes: "Cilantro + cheese, no onions",
        unitPriceCents: 1700,
      },
    ],
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    orderNumber: "MG-1052",
    customerId: null,
    customerName: "Hamza Ali",
    customerEmail: "hamza@example.com",
    customerZone: "Sterling",
    status: "In Prep",
    serviceDate: "2026-03-17",
    legacyDropDay: "Wednesday",
    fulfillmentMethod: "pickup",
    serviceWindow: "Pickup details confirmed after checkout",
    totalCents: 3120,
    customRequest: "Please text instead of calling.",
    paymentProvider: "Stripe",
    paymentStatus: "paid",
    createdAt: now,
    updatedAt: now,
    items: [
      {
        id: "oi-3",
        orderId: "22222222-2222-2222-2222-222222222222",
        menuItemId: "wings-karachi-6",
        name: "Karachi Hot Wings (6pc)",
        quantity: 1,
        notes: "Extra ranch on the side",
        unitPriceCents: 1500,
      },
      {
        id: "oi-4",
        orderId: "22222222-2222-2222-2222-222222222222",
        menuItemId: "bowl-chicken",
        name: "Chicken Bowl",
        quantity: 1,
        notes: "Light rice, extra cucumbers",
        unitPriceCents: 1500,
      },
    ],
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    orderNumber: "MG-1053",
    customerId: "cust-201",
    customerName: "Ayesha Khan",
    customerEmail: "ayesha@example.com",
    customerZone: "Herndon",
    status: "Picked Up",
    serviceDate: "2026-03-16",
    legacyDropDay: "Monday",
    fulfillmentMethod: "pickup",
    serviceWindow: "Pickup details confirmed after checkout",
    totalCents: 4200,
    customRequest: null,
    paymentProvider: "Stripe",
    paymentStatus: "paid",
    createdAt: "2026-03-16T17:10:00.000Z",
    updatedAt: "2026-03-16T19:00:00.000Z",
    items: [],
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    orderNumber: "MG-1054",
    customerId: "cust-missing",
    customerName: "Record With Missing Customer",
    customerEmail: null,
    customerZone: "Fairfax",
    status: "New",
    serviceDate: null,
    legacyDropDay: null,
    fulfillmentMethod: "pickup",
    serviceWindow: "Pickup details confirmed after checkout",
    totalCents: 1800,
    customRequest: null,
    paymentProvider: "Stripe",
    paymentStatus: "paid",
    createdAt: "2026-03-15T12:00:00.000Z",
    updatedAt: "2026-03-15T12:00:00.000Z",
    items: [],
  },
  {
    id: "55555555-5555-5555-5555-555555555555",
    orderNumber: "MG-1055",
    customerId: null,
    customerName: "Unlinked Pickup Record",
    customerEmail: null,
    customerZone: "Reston",
    status: "New",
    serviceDate: null,
    legacyDropDay: null,
    fulfillmentMethod: "pickup",
    serviceWindow: "Pickup details confirmed after checkout",
    totalCents: 2200,
    customRequest: null,
    paymentProvider: "Stripe",
    paymentStatus: "paid",
    createdAt: "2026-03-15T13:00:00.000Z",
    updatedAt: "2026-03-15T13:00:00.000Z",
    items: [],
  },
];

const inventory: InventoryItem[] = [
  {
    id: "inv-nihari",
    name: "Beef Nihari",
    unit: "portions",
    onHand: 18,
    parLevel: 10,
    status: "Healthy",
    lastUpdatedAt: now,
    notes: "Core protein for signature items.",
    linkedMenuItems: [{ id: "nihari-tacos", name: "Nihari Tacos" }],
  },
  {
    id: "inv-onions",
    name: "Red Pickled Onions",
    unit: "trays",
    onHand: 2,
    parLevel: 3,
    status: "Low",
    lastUpdatedAt: now,
    notes: "Critical bowl and roll garnish.",
    linkedMenuItems: [
      { id: "nihari-tacos", name: "Nihari Tacos" },
      { id: "lamb-sliders", name: "Lamb Sliders" },
      { id: "seekh-roll", name: "Seekh Kabob Roll" },
      { id: "bihari-roll", name: "Bihari Roll" },
      { id: "bowl-lamb", name: "Lamb Bowl" },
      { id: "bowl-chicken", name: "Chicken Bowl" },
    ],
  },
  {
    id: "inv-cilantro",
    name: "Cilantro",
    unit: "trays",
    onHand: 1,
    parLevel: 2,
    status: "Low",
    lastUpdatedAt: now,
    notes: "Runs fast on bowl-heavy service days.",
    linkedMenuItems: [
      { id: "bowl-lamb", name: "Lamb Bowl" },
      { id: "bowl-chicken", name: "Chicken Bowl" },
    ],
  },
];

const menu: MenuItem[] = [
  {
    id: "nihari-tacos",
    slug: "nihari-tacos",
    name: "Nihari Tacos",
    category: "signature",
    priceCents: 1800,
    availability: "Live",
    allocationLimit: 86,
    description: "Slow-braised nihari beef, pickled onion, herb chutney.",
    imageUrl: null,
    sortOrder: 10,
    isFeatured: true,
    notes: "Keep featured in ordering surfaces.",
  },
  {
    id: "lamb-sliders",
    slug: "lamb-sliders",
    name: "Lamb Sliders",
    category: "signature",
    priceCents: 1800,
    availability: "Live",
    allocationLimit: 63,
    description: "Spiced lamb patties, garlic toum, pickled red onion.",
    imageUrl: null,
    sortOrder: 20,
    isFeatured: true,
    notes: "Strong signature item with a premium lean.",
  },
  {
    id: "wings-karachi-6",
    slug: "wings-karachi-6",
    name: "Karachi Hot Wings (6pc)",
    category: "wings",
    priceCents: 1500,
    availability: "Live",
    allocationLimit: 78,
    description: "Bold heat with Karachi-style masala and a crisp finish.",
    imageUrl: null,
    sortOrder: 30,
    isFeatured: false,
    notes: null,
  },
  {
    id: "wings-karachi-12",
    slug: "wings-karachi-12",
    name: "Karachi Hot Wings (12pc)",
    category: "wings",
    priceCents: 2600,
    availability: "Live",
    allocationLimit: 78,
    description: "Bold heat with Karachi-style masala and a crisp finish.",
    imageUrl: null,
    sortOrder: 31,
    isFeatured: false,
    notes: null,
  },
  {
    id: "wings-honey-6",
    slug: "wings-honey-6",
    name: "Honey Garlic Lahori Wings (6pc)",
    category: "wings",
    priceCents: 1500,
    availability: "Live",
    allocationLimit: 78,
    description: "Sweet heat with a Lahori-style garlic finish.",
    imageUrl: null,
    sortOrder: 32,
    isFeatured: false,
    notes: null,
  },
  {
    id: "wings-honey-12",
    slug: "wings-honey-12",
    name: "Honey Garlic Lahori Wings (12pc)",
    category: "wings",
    priceCents: 2600,
    availability: "Live",
    allocationLimit: 78,
    description: "Sweet heat with a Lahori-style garlic finish.",
    imageUrl: null,
    sortOrder: 33,
    isFeatured: false,
    notes: null,
  },
  {
    id: "wings-buffalo-6",
    slug: "wings-buffalo-6",
    name: "Buffalo Masala Wings (6pc)",
    category: "wings",
    priceCents: 1500,
    availability: "Live",
    allocationLimit: 78,
    description: "Buffalo-style wings with a masala edge.",
    imageUrl: null,
    sortOrder: 34,
    isFeatured: false,
    notes: null,
  },
  {
    id: "wings-buffalo-12",
    slug: "wings-buffalo-12",
    name: "Buffalo Masala Wings (12pc)",
    category: "wings",
    priceCents: 2600,
    availability: "Live",
    allocationLimit: 78,
    description: "Buffalo-style wings with a masala edge.",
    imageUrl: null,
    sortOrder: 35,
    isFeatured: false,
    notes: null,
  },
  {
    id: "seekh-roll",
    slug: "seekh-roll",
    name: "Seekh Kabob Roll",
    category: "rolls",
    priceCents: 1400,
    availability: "Live",
    allocationLimit: 34,
    description: "Seekh kabob wrapped in paratha with chutney and onion.",
    imageUrl: null,
    sortOrder: 40,
    isFeatured: false,
    notes: null,
  },
  {
    id: "bihari-roll",
    slug: "bihari-roll",
    name: "Bihari Roll",
    category: "rolls",
    priceCents: 1400,
    availability: "Live",
    allocationLimit: 34,
    description: "Bihari-style beef wrapped in paratha with chutney and onion.",
    imageUrl: null,
    sortOrder: 41,
    isFeatured: false,
    notes: "Keep coverage flexible for catering-sized orders.",
  },
  {
    id: "chicken-shawarma",
    slug: "chicken-shawarma",
    name: "Chicken Shawarma Roll",
    category: "rolls",
    priceCents: 1400,
    availability: "Live",
    allocationLimit: 34,
    description: "Chicken shawarma wrapped in paratha with sauces and crunch.",
    imageUrl: null,
    sortOrder: 42,
    isFeatured: false,
    notes: null,
  },
  {
    id: "bowl-lamb",
    slug: "bowl-lamb",
    name: "Lamb Bowl",
    category: "bowls",
    priceCents: 1700,
    availability: "Live",
    allocationLimit: 71,
    description: "Tender lamb over basmati rice or greens with raita, green chutney, and your choice of bowl toppings.",
    imageUrl: null,
    sortOrder: 50,
    isFeatured: false,
    notes: "Strong upsell item.",
  },
  {
    id: "bowl-chicken",
    slug: "bowl-chicken",
    name: "Chicken Bowl",
    category: "bowls",
    priceCents: 1500,
    availability: "Live",
    allocationLimit: 71,
    description: "Marinated chicken over basmati rice or greens with raita, green chutney, and your choice of bowl toppings.",
    imageUrl: null,
    sortOrder: 51,
    isFeatured: false,
    notes: null,
  },
];

const customers: Customer[] = [
  {
    id: "cust-201",
    name: "Ayesha Khan",
    email: "ayesha@example.com",
    zone: "Herndon",
    totalOrders: 6,
    lifetimeValueCents: 24400,
    loyaltyTier: "High",
    notes: "Prefers extra herb chutney and earlier pickup windows.",
    lastOrderAt: now,
  },
  {
    id: "cust-202",
    name: "Hamza Ali",
    email: "hamza@example.com",
    zone: "Sterling",
    totalOrders: 4,
    lifetimeValueCents: 15700,
    loyaltyTier: "Rising",
    notes: "Prefers pickup updates by text.",
    lastOrderAt: null,
  },
  {
    id: "cust-203",
    name: "Fatima Noor",
    email: "fatima@example.com",
    zone: "Vienna",
    totalOrders: 8,
    lifetimeValueCents: 31800,
    loyaltyTier: "VIP",
    notes: "Often orders for small office groups and adds custom requests.",
    lastOrderAt: now,
  },
  {
    id: "cust-204",
    name: "Omar Siddiqui",
    email: "omar@example.com",
    zone: "Fairfax",
    totalOrders: 3,
    lifetimeValueCents: 9400,
    loyaltyTier: "Early",
    notes: "Likes mild spice on roll orders.",
    lastOrderAt: null,
  },
];

const emailUpdates: EmailUpdate[] = [
  {
    id: "reminder-1",
    email: "updates@example.com",
    source: "mogrillzva-website",
    signupLocation: "success-page",
    status: "Active",
    notes: "Signed up after checkout.",
    lastRequestedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "reminder-2",
    email: "fatima@example.com",
    source: "mogrillzva-website",
    signupLocation: "success-page",
    status: "Active",
    notes: null,
    lastRequestedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "reminder-3",
    email: "omar@example.com",
    source: "mogrillzva-website",
    signupLocation: "footer-form",
    status: "Unsubscribed",
    notes: null,
    lastRequestedAt: "2026-03-15T10:00:00.000Z",
    createdAt: "2026-03-01T10:00:00.000Z",
    updatedAt: "2026-03-15T10:00:00.000Z",
  },
];

const activity: OrderStatusEvent[] = [
  {
    id: "event-1",
    orderId: "11111111-1111-1111-1111-111111111111",
    fromStatus: "In Prep",
    toStatus: "Ready",
    orderVersion: 2,
    changedBy: "actor-demo-1",
    changedAt: "2026-03-17T20:40:00.000Z",
  },
  {
    id: "event-2",
    orderId: "33333333-3333-3333-3333-333333333333",
    fromStatus: "Ready",
    toStatus: "Picked Up",
    orderVersion: 3,
    changedBy: null,
    changedAt: "2026-03-16T19:00:00.000Z",
  },
  {
    id: "event-3",
    orderId: "missing-order-id",
    fromStatus: "New",
    toStatus: "Cancelled",
    orderVersion: 1,
    changedBy: "actor-demo-2",
    changedAt: "2026-03-16T18:30:00.000Z",
  },
  {
    id: "event-4",
    orderId: "44444444-4444-4444-4444-444444444444",
    fromStatus: "New",
    toStatus: "In Prep",
    orderVersion: 1,
    changedBy: null,
    changedAt: "2026-03-15T12:30:00.000Z",
  },
];

const insights: Insight[] = [
  {
    id: "insight-1",
    type: "prep",
    title: "Prep Recommendation",
    summary: "Increase lamb prep by 2 portions if bowl demand keeps holding.",
    confidence: 94,
    actionText: "Shift one tray worth of garnish support toward bowl assembly.",
    tone: "success",
    createdAt: now,
  },
  {
    id: "insight-2",
    type: "ops",
    title: "Operational Risk",
    summary: "Red pickled onions and cilantro are the first garnish bottlenecks.",
    confidence: 92,
    actionText: "Prep onions tonight and restock cilantro before the next service block starts.",
    tone: "danger",
    createdAt: now,
  },
];

export const mockDashboardSnapshot: DashboardSnapshot = {
  generatedAt: now,
  operations: {
    serviceDateLabel: "Today",
    status: "Pickup queue live",
    queueSummary: "2 active orders",
    serviceWindow: "Pickup details confirmed after checkout",
  },
  kpis: [
    { label: "Today's Orders", value: "37", delta: "37 next-day pickup", tone: "gold" },
    { label: "Revenue To Date", value: "$1,842", delta: "37 paid synced orders", tone: "green" },
    { label: "Low Stock Items", value: "4", delta: "Needs attention before prep", tone: "red" },
    { label: "Prep Confidence", value: "91%", delta: "Operator review", tone: "blue" },
  ],
  orders,
  inventory,
  menu,
  customers,
  emailUpdates,
  optionalSources: {
    subscribers: { status: "loaded", issue: null },
    activity: { status: "loaded", issue: null },
  },
  activity,
  activityScope: "order-status-events-only",
  insights,
};

export function cloneMockSnapshot(): DashboardSnapshot {
  return structuredClone(mockDashboardSnapshot);
}
